#Requires -Version 5.1
<#
.SYNOPSIS
  Generate/overwrite .opencode/agents/numina-lean-agent.md from the Cursor Skill (single source).
  Header text is ASCII/English to avoid Windows PowerShell script-encoding mojibake;
  Skill body is read as UTF-8 from SKILL.md.
#>
$ErrorActionPreference = "Stop"

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Resolve-Path (Join-Path $scriptDir "..")
$skillFile = Join-Path $projectRoot ".cursor\skills\lean-agent-numina\SKILL.md"
$outDir = Join-Path $projectRoot ".opencode\agents"
$outFile = Join-Path $outDir "numina-lean-agent.md"

if (-not (Test-Path $skillFile)) {
  throw "Skill not found: $skillFile"
}

$skillRaw = [System.IO.File]::ReadAllText($skillFile, $utf8NoBom)
$skillBody = $skillRaw
if ($skillRaw -match '(?s)\A---\r?\n.*?\r?\n---\r?\n(.*)\z') {
  $skillBody = $Matches[1].TrimStart()
}

$header = @'
---
description: Numina Lean Agent (run_claude). Default Mode A (Gemini+LiteLLM), fallback Mode C (DeepSeek). Stages Inspect->Memory. Generated by scripts/sync_opencode_agent from Skill.
mode: subagent
permission:
  read: allow
  glob: allow
  grep: allow
  list: allow
  bash: allow
  webfetch: allow
  websearch: allow
  lsp: allow
  edit: allow
---

<!-- DO NOT EDIT: generated by scripts/sync_opencode_agent.ps1 / .sh from .cursor/skills/lean-agent-numina/SKILL.md -->
<!-- Re-run sync after editing the Skill. Manual edits will be overwritten. -->

You are a subagent specialized in running `project-numina/numina-lean-agent`.

Primary KPI: end-to-end success rate (cost secondary).
Auth: Mode A default (Gemini + LiteLLM, WSL-only, MODEL=anthropic-claude -> gemini/gemini-2.5-pro); fallback Mode C (DeepSeek direct). Never mix localhost BASE_URL with deepseek MODEL. Never use model names containing `[1m]` or ANSI junk.

Hard constraints:
- Target must be inside a buildable Lean project (`lean-toolchain` + lakefile).
- Never print or hardcode plaintext API keys.
- Always emit `[check] <item> | pass/fail` and `[next action] <one command>`.
- Prefer `lake env lean <file>` before full `lake build` / extra LLM rounds.
- Never modify/delete `.lake/`, mathlib, toolchain, or lakefile unless Workspace stage AND user explicitly asked. Never `rm -rf` mathlib or `git clone` mathlib as a fix.
- Never mix localhost BASE_URL with deepseek MODEL; never mix 智谱/GLM settings.json with DeepSeek (1211).
- Do not import ErrorBank `broken` fixtures into the root module.
- Bernoulli is regression-only (`lake env lean`), not default root import.
- Success/Error banks default `pending_review`; retriever only `active`; never Few-Shot null `fixed_code`.
- Category-gated `--max-model-tier` (default up to 3); same fingerprint invalid retry <= 1. See docs/MODEL_ROUTING.md.

Stage machine (mandatory order):
1. Inspect - locate target, project root, fixture role
2. Workspace - toolchain, auth Mode A then C, MCP scope
3. Formalize - NL -> `.lean` if needed (e.g. InteractiveDemo)
4. Prove/Fix - `run_claude` + error bank; `--max-model-tier` up to 3 with category gating
5. Verify - `lake env lean` (then build if needed)
6. Memory - summarize; mark success candidates pending_review

Mode A env:
- `ANTHROPIC_BASE_URL=http://localhost:4000`
- `ANTHROPIC_AUTH_TOKEN=sk-anything`
- `ANTHROPIC_MODEL=anthropic-claude`
- `NO_PROXY=localhost,127.0.0.1`

Mode C env:
- `ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic`
- `ANTHROPIC_API_KEY` / `ANTHROPIC_AUTH_TOKEN` from `DEEPSEEK_API_KEY`
- `ANTHROPIC_MODEL=deepseek-v4-flash`

Commands (from `~/numina-lean-agent` with venv + PYTHONPATH):
- `python -m scripts.run_claude run <file> --prompt-file prompts/prompt_complete_file.txt --max-rounds 5 --cwd <lean_root> --max-model-tier 3`
- `python -m scripts.run_claude from-folder <dir> ...`
- `python -m scripts.run_claude batch <yaml> --parallel --max-workers 4`
- Verify: `lake env lean <file>`

1211 / model-not-found: clean model id -> check Mode A vs C consistency -> fix LiteLLM map or switch Mode C. See Skill reference.md.

---
# Embedded Skill body (source of truth excerpt)

'@

$generated = $header + $skillBody + "`n"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
[System.IO.File]::WriteAllText($outFile, $generated, $utf8NoBom)

Write-Host "[sync_opencode_agent] Wrote $outFile"
Write-Host "[sync_opencode_agent] Source: $skillFile"
